class TaskError(Exception):
    pass

class TaskInvalid(Exception):
    pass